name: fjghrd
description: "HRD Fratekindo Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  background_downloader: ^8.9.4
  currency_text_input_formatter: ^2.2.8
  dotted_border: ^2.1.0
  fl_chart: ^0.70.2
  get: ^4.6.6
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  pluto_grid: ^8.0.0
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700