name: fjghrd
description: "HRD Fratekindo Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  background_downloader: ^8.5.2
  currency_text_input_formatter: ^2.2.3
  dotted_border: ^2.1.0
  fl_chart: ^0.68.0
  get: ^4.6.6
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  mime: ^1.0.5
  path_provider: ^2.1.3
  pluto_grid: ^8.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700